import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const project=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),base=path.join(project,'dist/client');async function walk(dir){return(await Promise.all((await fs.readdir(dir,{withFileTypes:true})).map(x=>x.isDirectory()?walk(path.join(dir,x.name)):[path.join(dir,x.name)]))).flat();}const pages=(await walk(base)).filter(x=>x.endsWith('.html'));const missing=[];let inlineScripts=0;
for(const file of pages){const s=await fs.readFile(file,'utf8');for(const match of s.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/gi)){if(/type="application\/.*json"/.test(match[1]))continue;if(match[2].trim()){try{new Function(match[2]);}catch(e){throw Error(path.relative(base,file)+' inline JavaScript: '+e.message);}inlineScripts++;}}
const markup=s.replace(/(<script[^>]*>)[\s\S]*?<\/script>/gi,'$1</script>');const ids=[...markup.matchAll(/\sid="([^"]+)"/g)].map(x=>x[1]);assert.equal(new Set(ids).size,ids.length,'duplicate element IDs: '+file);
for(const match of markup.matchAll(/\b(src|href|poster)="([^"]+)"/g)){const value=match[2];if(/^(https?:|mailto:|tel:|#|data:|javascript:)/.test(value))continue;const name=value.split(/[?#]/)[0];if(!name)continue;let target=name.startsWith('/')?path.join(base,name.slice(1)):path.resolve(path.dirname(file),name);try{const st=await fs.stat(target);if(st.isDirectory())target=path.join(target,'index.html');await fs.access(target);}catch{missing.push({page:path.relative(base,file),value});}}
for(const match of markup.matchAll(/srcset="([^"]+)"/g))for(const item of match[1].split(',')){const value=item.trim().split(/\s+/)[0];const target=value.startsWith('/')?path.join(base,value.slice(1)):path.resolve(path.dirname(file),value);try{await fs.access(target);}catch{missing.push({page:path.relative(base,file),value});}}}
await fs.mkdir(path.join(project,'reports'),{recursive:true});await fs.writeFile(path.join(project,'reports/local-link-check.json'),JSON.stringify(missing,null,2));assert.equal(missing.length,0,JSON.stringify(missing.slice(0,10)));for(const prefix of ['','zh/','en/']){const s=await fs.readFile(path.join(base,prefix,'index.html'),'utf8');assert.match(s,/<h1>/);assert.doesNotMatch(s,/preview-banner|name="robots" content="noindex/);assert.match(s,/rel="canonical"/);assert.match(s,/rel="alternate"/);}
const cfg=await fs.readFile(path.join(base,'assets/supabase-config.js'),'utf8');const key=cfg.match(/key\s*:\s*['"]([^'"]+)/)?.[1];if(key?.split('.').length===3){const payload=JSON.parse(Buffer.from(key.split('.')[1],'base64url'));assert.equal(payload.role,'anon','privileged key must not be public');}
console.log(JSON.stringify({pages:pages.length,inlineScripts,missingLocalReferences:missing.length,serverVisibleLocales:3,publicKeyChecked:true}));
