import {decorateServiceIllustrationHtml} from './service-illustrations.mjs';
import fs from 'node:fs/promises';import crypto from 'node:crypto';import path from 'node:path';import {fileURLToPath} from 'node:url';
const project=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),repo=path.resolve(process.argv[2]||path.join(project,'..')),publicDir=path.join(project,'public');
const mapping=JSON.parse(await fs.readFile(path.join(project,'reports/image-map.json'))),manifest=JSON.parse(await fs.readFile(path.join(project,'reports/image-responsive-manifest.json')));const zhPairs=(await fs.readFile(path.join(project,'scripts/zh-repairs.tsv'),'utf8')).split('\n').filter(Boolean).map(x=>x.split('\t'));
const illustrationVersion=crypto.createHash('sha256').update(await fs.readFile(path.join(publicDir,'assets/service-illustrations.css'))).digest('hex').slice(0,12);
const excluded=['index.html','admin.html','inquiry-status.html','privacy.html','404.html'];let updated=0;
for(const locale of ['','zh','en']){const dir=path.join(repo,locale);for(const filename of await fs.readdir(dir)){if(!/^[a-z]+(?:-[a-z]+)*\.html$/.test(filename)||excluded.includes(filename))continue;const file=path.join(dir,filename);let s=await fs.readFile(file,'utf8');
 s=s.replace(/<script[^>]*src="https:\/\/www\.googletagmanager\.com[^>]*><\/script>/g,'').replace(/<script>window\.dataLayer=[\s\S]*?<\/script>/g,'');
 if(filename!=='online-guide.html')s=s.replace(/<script[^>]*src="(?:\.\.\/)?assets\/inquiry-records\.js"[^>]*><\/script>/g,'');
 if(locale==='zh'){for(const [a,b]of zhPairs)if(b!==undefined)s=s.replaceAll(a,b);for(const [a,b]of Object.entries({'인韩元':'人数','韩元가계':'袁家界','현지가이드':'当地导游','데이旅行':'一日游','미선택':'未选择','미입력':'未填写','매일':'每日','시내':'市区','1인':'每人','8시간':'8小时','6시간':'6小时','0일':'0天','1일':'1天','2명':'2人','2개':'2件'}))s=s.replaceAll(a,b);const extras=(await fs.readFile(path.join(project,'scripts/zh-repairs-extra.tsv'),'utf8')).split('\n').filter(Boolean).map(x=>x.split('\t')).sort((a,b)=>b[0].length-a[0].length);for(const [a,b]of extras)s=s.replaceAll(a,b);s=s.replaceAll('}월','}月').replaceAll('}일','}日').replaceAll('}명','}人').replaceAll('}실','}间');s=s.replace(/박 /g,'晚 ').replace(/일(?=[ )·])/g,'天').replace(/명(?=[ /·,)])/g,'人').replace(/실(?=[ /·,)])/g,'间').replace(/월 (?=\d)/g,'月 ').replace(/일(?=[: ·])/g,'日');s=s.replaceAll('${n}日','${n}天').replace('<option>韩语</option><option>中文</option><option>韩语与中文均可</option>','<option>韩语</option><option selected>中文</option><option>韩语与中文均可</option>');s=s.replaceAll("[...ko,'','──────── 中文版 ────────','',...zh]",'[...zh]').replaceAll("[...inquiryKo,'','──────── 中文版 ────────','',...inquiryZh]",'[...inquiryZh]').replace("zh:clean(parts[1]||'','zh')","zh:clean(parts[1]||parts[0]||'','zh')").replace("$('#comboInquiry').value=ko.filter(x=>x!==null).join('\\n');","$('#comboInquiry').value=ko.filter(x=>x!==null).join('\\n').split('──────── 中文版 ────────').pop().trim();");s=s.replaceAll('../../assets/','../assets/');}
 for(const [old,target]of mapping)s=s.replaceAll(old.slice(1),target.slice(1));
 s=s.replace(/<img\b[^>]*>/g,tag=>{const src=tag.match(/\bsrc="([^"]+)"/)?.[1];if(!src||/^https?:/.test(src))return tag;const url='/'+path.relative(repo,path.resolve(dir,src));const meta=manifest[url];if(!meta)return tag;const srcset=meta.variants.map(v=>path.relative(dir,path.join(repo,v.url.slice(1)))+' '+v.width+'w').join(', ');let out=tag.replace(/\s(srcset|sizes|decoding)="[^"]*"/gi,'');out=out.replace('<img','<img decoding="async" srcset="'+srcset+'" sizes="(max-width:760px) 100vw,50vw"');if(url.includes('huangshizhai-cableway-jpg'))out=out.replace(/alt="[^"]*"/,'alt="'+(locale==='zh'?'张家界国家森林公园南门景色':locale==='en'?'Zhangjiajie forest scenery':'장가계 국가삼림공원 남문 풍경')+'"');return out;});
 s=s.replace(/<video\b[^>]*>/g,tag=>tag.replace(/\sautoplay\b/g,'').replace(/\spreload="[^"]*"/g,'').replace('<video','<video preload="none"'));const prefix=locale?'../':'';s=s.replace(/<link\b[^>]*href="(?:\.\.\/)?assets\/redesign\.css"[^>]*>/g,'').replace(/<script\b[^>]*src="(?:\.\.\/)?assets\/redesign\.js"[^>]*><\/script>/g,'');s=s.replace('</head>','<link rel="stylesheet" href="'+prefix+'assets/redesign.css"></head>').replace('</body>','<script src="'+prefix+'assets/redesign.js"></script></body>');s=decorateServiceIllustrationHtml(s,{filename,locale,version:illustrationVersion});const dest=path.join(publicDir,locale,filename);await fs.mkdir(path.dirname(dest),{recursive:true});await fs.writeFile(dest,s.replace(/[ \t]+$/gm,''));updated++;}}
async function copyAssets(dir){for(const item of await fs.readdir(dir,{withFileTypes:true})){const src=path.join(dir,item.name),dest=path.join(publicDir,path.relative(repo,src));if(item.isDirectory()){await fs.mkdir(dest,{recursive:true});await copyAssets(src);}else{if(/^index-[\w-]+\.(js|css)$/.test(item.name)||['redesign.js','redesign.css','inquiry-status.js','brand-system.js','brand-system.css','video-guides.js','video-player.mjs','video-guides.css','video-guides.json','orange-hat-portrait.png','service-illustrations.css'].includes(item.name)||path.relative(repo,src).startsWith('assets/brand/illustrations/'))continue;let same=false;try{if((await fs.stat(src)).size===(await fs.stat(dest)).size){const [a,b]=await Promise.all([fs.readFile(src),fs.readFile(dest)]);same=crypto.createHash('sha256').update(a).digest('hex')===crypto.createHash('sha256').update(b).digest('hex');}}catch{}if(!same)await fs.copyFile(src,dest);}}}await copyAssets(path.join(repo,'assets'));console.log('Synced '+updated+' current legacy service/content pages into the release build.');
