import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import crypto from 'node:crypto';
const read=p=>fs.readFile(new URL('../'+p,import.meta.url),'utf8');
test('approved orange-hat portrait is byte-for-byte unchanged',async()=>{const b=await fs.readFile(new URL('../public/assets/brand/orange-hat-portrait.png',import.meta.url));assert.equal(crypto.createHash('sha256').update(b).digest('hex'),'ee97d73dc0ea52177bdfbf995f9051b922b40ebbce2713ba1e3e38d64a927291');});
test('service symbols keep six distinct semantic entries and are decorative',async()=>{const s=await read('src/ServiceIcon.jsx');for(const k of ['ticket','vehicle','guide','day','custom','support'])assert.match(s,new RegExp(k+':'));assert.match(s,/aria-hidden="true"/);assert.match(s,/focusable="false"/);});
test('curated film records have exact valid IDs and three readable locales',async()=>{const data=JSON.parse(await read('src/video-guides.json'));assert.ok(data.length>=19);for(const v of data){assert.match(v.id,/^[\w-]{11}$/);assert.ok(v.url.endsWith('/'+v.id)||new URL(v.url).searchParams.get('v')===v.id);assert.equal(new URL(v.thumbnail).hostname,'i.ytimg.com');assert.ok(v.thumbnail.includes('/'+v.id+'/'));for(const l of ['ko','zh','en'])assert.ok(v.title[l]?.length>4);assert.notEqual(v.id,'7QMuXRdhyHg');}});
test('film widgets are optional, lazy, no-autoplay links with a fallback',async()=>{const s=await read('src/VideoGuides.jsx');assert.match(s,/loading="lazy"/);assert.match(s,/onError=/);assert.match(s,/video-image-fallback/);assert.doesNotMatch(s,/<iframe|autoplay=/);assert.match(s,/rel="noopener noreferrer"/);assert.match(s,/selectVideos\(videos,\{destination,category\},6\)/);const legacy=await read('public/assets/video-guides.js');assert.match(legacy,/createVideoPlayer/);assert.match(legacy,/addEventListener\('error'/);});
test('published video data and styles match React source',async()=>{assert.equal(await read('src/video-guides.json'),await read('public/assets/video-guides.json'));assert.equal(await read('src/video-guides.css'),await read('public/assets/video-guides.css'));});
test('motion and keyboard focus retain accessible alternatives',async()=>{const s=await read('src/styles.css');assert.match(s,/prefers-reduced-motion:reduce/);assert.match(s,/intent-card:focus-visible/);assert.match(await read('src/video-guides.css'),/prefers-reduced-motion:reduce/);});
test('production React source has no preview-only network or submission guard',async()=>{for(const p of ['src/App.jsx','src/Storefront.jsx'])assert.doesNotMatch(await read(p),/preview-guard|brand-system\.js|window\.fetch\s*=/);});
