import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
import {videoEmbedUrl,selectVideos,matchesVideoCategory,serviceVideoContext} from '../src/video-player.mjs';
import {decorateBrandHtml} from '../../scripts/apply-brand-system.mjs';
const data=JSON.parse(await fs.readFile(new URL('../src/video-guides.json',import.meta.url),'utf8'));
test('player embeds are validated and never autoplay',()=>{const url=new URL(videoEmbedUrl('s9mISSLq3T8'));assert.equal(url.hostname,'www.youtube-nocookie.com');assert.equal(url.searchParams.get('autoplay'),'0');assert.equal(url.searchParams.get('playsinline'),'1');for(const id of ['','bad/../../x','https://example.com','<script>'])assert.throws(()=>videoEmbedUrl(id));});
test('homepage discovery has six diverse videos and topic filters',()=>{const home=selectVideos(data,{page:'home',destination:'zhangjiajie'},6);assert.equal(home.length,6);assert.equal(new Set(home.map(x=>x.id)).size,6);for(const c of ['transport','prepare','local'])assert.ok(home.some(v=>matchesVideoCategory(v,c)));assert.ok(selectVideos(data,{page:'home',destination:'zhangjiajie',category:'transport'},6).every(x=>x.servicePaths.includes('vehicles.html')));});
test('service matching is bounded, relevant and destination-aware',()=>{for(const page of ['tickets.html','day-tours.html','private-tour.html','local-guide.html','vehicles.html','online-guide.html']){const list=selectVideos(data,{page,destination:'zhangjiajie'},4);assert.ok(list.length>=2&&list.length<=4,page);assert.ok(list.every(v=>v.servicePaths.includes(page)&&v.destination==='zhangjiajie'));}const hainan=selectVideos(data,{page:'day-tours.html',destination:'hainan'},4);assert.ok(hainan.length>=2);assert.ok(hainan.every(v=>v.destination==='hainan'));});
test('selected attraction ranks first',()=>{const list=selectVideos(data,{page:'tickets.html',destination:'zhangjiajie',attraction:'tianmen'},4);assert.ok(list[0].attractions.includes('tianmen'));});
test('whole thumbnails and portrait player constraints are present',async()=>{const css=await fs.readFile(new URL('../src/video-guides.css',import.meta.url),'utf8');assert.match(css,/object-fit:contain/);assert.match(css,/\.video-player-screen\.is-short[^}]*aspect-ratio:9\/16/);assert.match(css,/40\.5svh/);});
test('player uses valid referrer and removes iframe on lifecycle teardown',async()=>{const s=await fs.readFile(new URL('../src/video-player.mjs',import.meta.url),'utf8');assert.match(s,/strict-origin-when-cross-origin/);assert.match(s,/querySelectorAll\('iframe'\).*frame=>frame\.remove/);for(const name of ['pagehide','popstate','keydown'])assert.ok(s.includes(`removeEventListener('${name}'`));assert.match(s,/focusTarget\.focus\(\)/);assert.doesNotMatch(s,/allow='[^']*autoplay/);});
test('published player module equals source and survives rebuild',async()=>{const root=new URL('../',import.meta.url);assert.equal(await fs.readFile(new URL('src/video-player.mjs',root),'utf8'),await fs.readFile(new URL('public/assets/video-player.mjs',root),'utf8'));assert.match(await fs.readFile(new URL('scripts/sync-legacy.mjs',root),'utf8'),/'video-player\.mjs'/);});
test('shared asset cache versions replace old versions idempotently',()=>{const input='<html><head><link rel="stylesheet" href="/assets/brand-system.css?v=old"><script defer src="/assets/brand-system.js?v=old"></script><script src="/assets/video-guides.js?v=old" defer></script></head><body><main>Contents</main></body></html>';const html=decorateBrandHtml(input,'tickets.html','fresh123');assert.equal(decorateBrandHtml(html,'tickets.html','fresh123'),html);assert.equal((html.match(/brand-system\.js/g)||[]).length,1);assert.equal((html.match(/video-guides\.js/g)||[]).length,1);assert.equal((html.match(/\?v=fresh123/g)||[]).length,3);assert.ok(!html.includes('?v=old'));});

test('hidden unrelated legacy forms cannot leak video destination or attraction',()=>{
 const unrelated={querySelector(){throw Error('Unrelated hidden form was read');}};
 for(const page of ['vehicles.html','local-guide.html','online-guide.html','private-tour.html'])assert.deepEqual(serviceVideoContext(page,unrelated,'https://localtourchina.com/'+page),{page,destination:'zhangjiajie',attraction:''});
 const ticketDoc={querySelector(selector){assert.equal(selector,'#service-ticket .config.active');return {id:'config-forest'};}};
 assert.deepEqual(serviceVideoContext('tickets.html',ticketDoc,'https://localtourchina.com/tickets.html'),{page:'tickets.html',destination:'zhangjiajie',attraction:'forest'});
 const dayDoc={querySelector(selector){assert.equal(selector,'input[name="dayProduct"]:checked');return {value:'sanya-monkey'};}};
 assert.equal(serviceVideoContext('day-tours.html',dayDoc,'https://localtourchina.com/day-tours.html').destination,'hainan');
 assert.equal(serviceVideoContext('vehicles.html',unrelated,'https://localtourchina.com/vehicles.html?destination=hainan').destination,'hainan');
});
