import React,{useEffect,useRef,useState} from 'react';
import {DRAFT_KEY,STORAGE_KEY,serviceNames,initialDraft,partyLimit,validateDraft,dateLabel,inquiryText,savePreview} from './consultation.mjs';
import './styles.css';
import Storefront from './Storefront.jsx';
import {catalogInquiry,packageTitle} from './trip-catalog.mjs';
import ReviewStories from './ReviewStories.jsx';
import imageManifest from './image-manifest.json';
const responsiveImage=(src,sizes)=>({src,srcSet:imageManifest[src]?.srcSet,sizes,decoding:'async'});
import {submitInquiry} from './production.mjs';
const LIVE=import.meta.env?.VITE_LTC_MODE==='production';
import {localize,translate} from './locales.jsx';
const KAKAO='https://pf.kakao.com/_hvrmn/chat';
const external={target:'_blank',rel:'noopener noreferrer'};
const prices=[{id:'forest',name:'무릉원 핵심 완전 정복',description:'국가삼림공원·점심·한국어 가이드·차량·공연',price:280000,image:'forest.jpg',url:'/day-tours.html'}, {id:'tianmen',name:'천문산 클래식 하루 투어',description:'천문산·점심·한국어 가이드·시내 차량',price:210000,image:'/assets/media/attractions/tianmen-cliff-jpg-1080.webp',url:'/day-tours.html'}, {id:'canyon',name:'황룡동·대협곡 하루 투어',description:'동굴·유리다리·점심·한국어 가이드·차량',price:250000,image:'canyon.jpg',url:'/day-tours.html'}];
const money=n=>new Intl.NumberFormat('ko-KR').format(n)+'원';
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function track(event,details={}){if(LIVE)return;try{const key='ltc-preview-events';const items=JSON.parse(localStorage.getItem(key)||'[]');localStorage.setItem(key,JSON.stringify([...items,{event,scope:'preview',...details,time:new Date().toISOString()}].slice(-200)));}catch{}}
function startState(){const p=new URLSearchParams(location.search);const reference=p.get('reference');if(reference){try{const records=JSON.parse(sessionStorage.getItem('ltc-live-receipts')||localStorage.getItem(STORAGE_KEY)||'[]');const record=records.find(x=>x.reference===reference);if(record)return{view:'success',record,mode:record.mode};}catch{}return{view:'missing',mode:'private'};}return{view:p.get('view')==='consult'?'consult':'home',mode:['private','single','help'].includes(p.get('mode'))?p.get('mode'):'private'};}
export default function App(){
 const requestedLang=new URLSearchParams(location.search).get('lang')||location.pathname?.split('/')[1];const lang=['zh','en'].includes(requestedLang)?requestedLang:'ko';
 const initial=useRef(startState());
 const [view,setView]=useState(initial.current.view),[record,setRecord]=useState(initial.current.record||null),[menu,setMenu]=useState(false),[errors,setErrors]=useState({}),[saving,setSaving]=useState(false),[failed,setFailed]=useState(false),[failureCode,setFailureCode]=useState(''),[notice,setNotice]=useState(''),[failureTest,setFailureTest]=useState(false),[draftStored,setDraftStored]=useState(true);
 const [draft,setDraft]=useState(()=>{let base=initialDraft(initial.current.mode);try{const saved=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');if(saved)base={...base,...saved,mode:initial.current.mode};}catch{}const service=new URLSearchParams(location.search).get('service');if(serviceNames[service])base.services=[service];try{const selected=JSON.parse(sessionStorage.getItem('ltc-selected-conditions')||'null');if(selected){base.configuration=selected; for(const key of ['people','date','contact','nickname','hotel','flight'])if(selected[key]&&(!['contact','nickname'].includes(key)||!base[key]?.trim()))base[key]=selected[key];if(selected.date)base.dateMode='exact';else if(selected.dateDescription){base.dateMode='unknown';base.date='';base.month='';}if(selected.services?.length)base.services=selected.services;else if(serviceNames[selected.service])base.services=[selected.service];sessionStorage.removeItem('ltc-selected-conditions');}}catch{}return base;});
 const heading=useRef(null),copyArea=useRef(null),saveLock=useRef(false),formStarted=useRef(false);
 useEffect(()=>{const handle=()=>{const next=startState();setView(next.view);setRecord(next.record||null);setMenu(false);if(next.view==='consult')setDraft(d=>history.state?.ltcDraft?{...initialDraft(next.mode),...history.state.ltcDraft,mode:next.mode}:d.mode===next.mode?d:initialDraft(next.mode));};window.addEventListener('popstate',handle);return()=>window.removeEventListener('popstate',handle)},[]);
 useEffect(()=>{try{history.replaceState({...history.state,ltcDraft:draft},'',location.href);}catch{}},[draft,view]);
 useEffect(()=>{try{localStorage.setItem(DRAFT_KEY,JSON.stringify(draft));setDraftStored(true)}catch{setDraftStored(false)}},[draft]);
 useEffect(()=>{const header=document.querySelector('.site-header');const measure=()=>{const position=header?getComputedStyle(header).position:'';document.documentElement.style.setProperty('--sticky-header-height',((position==='sticky'||position==='fixed')?Math.ceil(header.getBoundingClientRect().height):0)+'px');};measure();const observer=typeof ResizeObserver!=='undefined'?new ResizeObserver(measure):null;if(header)observer?.observe(header);return()=>observer?.disconnect();},[]);
 useEffect(()=>{document.documentElement.lang=lang==='zh'?'zh-CN':lang;if(view!=='home'){heading.current?.focus();window.scrollTo({top:0,behavior:'instant'});}document.title=view==='home'?({ko:'로투차 | 장가계·하이난 여행',zh:'罗途查 | 张家界与海南旅行',en:'LocalTourChina | Zhangjiajie & Hainan trips'}[lang]):view==='success'?(LIVE?{ko:'상담 접수 | 로투차',zh:'咨询已提交 | 罗途查',en:'Inquiry received | LocalTourChina'}[lang]:'Preview inquiry | LocalTourChina'):{ko:'여행 상담 | 로투차',zh:'旅行咨询 | 罗途查',en:'Trip inquiry | LocalTourChina'}[lang];},[view]);
 useEffect(()=>{if(draftStored||view!=='consult')return;const guard=e=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[draftStored,view]);
 function go(next,mode=draft.mode,saved=null){const url=new URL(location.href);url.pathname=lang==='ko'?'/':'/'+lang+'/index.html';url.search='';if(next==='home'){try{const source=new URL(draft.configuration?.sourcePath||location.href,location.origin);for(const key of ['destination','product','pax'])if(source.searchParams.has(key))url.searchParams.set(key,source.searchParams.get(key));}catch{}}if(lang!=='ko')url.searchParams.set('lang',lang);if(next==='consult'){url.searchParams.set('view','consult');url.searchParams.set('mode',mode);}if(next==='success'){url.searchParams.set('reference',saved.reference);}history.pushState({},'',url);setView(next);setRecord(saved);setMenu(false);setNotice('');}
 function languageUrl(next){const url=new URL(location.href||((location.pathname||'/')+(location.search||'')),'https://localtourchina.com');url.pathname=next==='ko'?'/':'/'+next+'/index.html';if(next==='ko')url.searchParams.delete('lang');else url.searchParams.set('lang',next);return url.pathname+url.search+url.hash;}
 function beginPackage(product,pax){
  const sourcePath=(lang==='ko'?'/':'/'+lang+'/index.html')+'?destination=zhangjiajie&product='+encodeURIComponent(product.id)+'&pax='+pax;
  const configuration={service:'private',services:['private'],language:lang,sourcePath,productId:product.id,productTitle:packageTitle(product,lang),people:String(pax),inquiryText:catalogInquiry(product,pax,lang)};
  history.replaceState(history.state,'',sourcePath);
  setDraft(d=>({...d,mode:'private',services:['private'],people:String(pax),configuration,consent:false}));setErrors({});setFailed(false);go('consult','private');
 }
 function beginDestinationHelp(destination){
  const title=destination==='hainan'?({ko:'하이난·싼야',zh:'海南·三亚',en:'Hainan · Sanya'}[lang]):({ko:'장가계·후난',zh:'张家界·湖南',en:'Zhangjiajie · Hunan'}[lang]);
  const inquiry=({ko:'희망 여행지: ',zh:'希望目的地：',en:'Destination preference: '}[lang])+title;
  setDraft(d=>({...d,mode:'help',services:['help'],configuration:{service:'help',services:['help'],language:lang,sourcePath:(lang==='ko'?'/':'/'+lang+'/index.html')+'?destination='+destination,inquiryText:inquiry},consent:false}));setErrors({});setFailed(false);go('consult','help');
 }
 function begin(mode){formStarted.current=false;track('journey_select',{mode});setDraft(d=>d.mode===mode?d:{...d,mode,services:initialDraft(mode).services,configuration:null});setErrors({});setFailed(false);go('consult',mode);}
 function nav(event,id){event.preventDefault();if(view!=='home'){go('home');setTimeout(()=>document.getElementById(id)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'}),0);}else document.getElementById(id)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});setMenu(false);}
 function update(key,value){if(!formStarted.current){track('form_start',{mode:draft.mode});formStarted.current=true;}setDraft(d=>({...d,[key]:value}));setErrors(e=>{const next={...e};delete next[key];return next});if(!['network','response'].includes(failureCode))setFailed(false);}
 function toggleService(key){if(!formStarted.current){track('form_start',{mode:draft.mode});formStarted.current=true;}setDraft(d=>({...d,services:d.services.includes(key)?d.services.filter(x=>x!==key):[...d.services,key]}));setErrors(e=>({...e,services:undefined}));}
 async function submit(event){event.preventDefault();if(saveLock.current)return;const issues=validateDraft(draft);setErrors(issues);if(Object.keys(issues).length){track('validation_error');requestAnimationFrame(()=>document.querySelector('[aria-invalid="true"]')?.focus());return;}saveLock.current=true;setSaving(true);setFailed(false);track('save_start');await new Promise(r=>setTimeout(r,450));try{if(failureTest){setFailureTest(false);throw Error('preview failure');}const saved=LIVE?await submitInquiry(draft,lang,window.LOCALTOUR_SUPABASE):savePreview(draft);if(LIVE){try{const receipts=JSON.parse(sessionStorage.getItem('ltc-live-receipts')||'[]');sessionStorage.setItem('ltc-live-receipts',JSON.stringify([...receipts,saved]));localStorage.removeItem(DRAFT_KEY);}catch{}}track('save_success',{reference:saved.reference});go('success',draft.mode,saved);}catch(error){setFailed(true);setFailureCode(error.code||'server');track('save_failure');}finally{saveLock.current=false;setSaving(false);}}
 async function copy(text){try{await navigator.clipboard.writeText(text);setNotice('복사했습니다. 카카오톡에 붙여넣고 전송해 주세요.');}catch{setNotice('자동 복사가 되지 않았습니다. 아래 내용을 선택해 직접 복사해 주세요.');requestAnimationFrame(()=>{copyArea.current?.focus();copyArea.current?.select();});}}
 const fieldProps=(key)=>({id:key,name:key,value:draft[key],onChange:e=>update(key,e.target.value),'aria-invalid':errors[key]?'true':undefined,'aria-describedby':errors[key]?`${key}-error`:undefined});
 const ErrorText=({name})=>errors[name]?<p aria-live="polite" className="field-error" id={`${name}-error`}>{translate(errors[name],lang)}</p>:null;
 const text=inquiryText(record||draft,record?.reference||'',lang,LIVE);
 return localize(<>
 {!LIVE&&<div className="preview-banner"><span>디자인 미리보기</span><span>상담 내용은 이 브라우저에만 저장되며, 실제 예약은 접수되지 않습니다.</span></div>}
 <a className="skip-link" href="#main">본문으로 바로가기</a>
 <header className="site-header"><div className="header-inner"><a className="wordmark" href="?" onClick={e=>{e.preventDefault();if(lang!=='ko'){location.href='/'+lang+'/index.html';return;}go('home');}} aria-label="로투차 홈">로투차</a><button className="menu-button" aria-expanded={menu} aria-controls="navigation" onClick={()=>setMenu(!menu)}>{menu?'닫기':'메뉴'}</button><nav id="navigation" className={menu?'open':''} aria-label="주요 메뉴"><a href="/booking.html">상세 서비스</a><a href="#services" onClick={e=>nav(e,'services')}>여행 서비스</a><a href="#reviews" onClick={e=>nav(e,'reviews')}>실제 여행 후기</a><a href="/travel-info.html" {...external}>여행 준비</a><a href="#company" onClick={e=>nav(e,'company')}>회사 소개</a></nav><div className="locale-links" aria-label="언어 선택"><a href={languageUrl('ko')} lang="ko" aria-current={lang==='ko'?'page':undefined}>KO</a><a href={languageUrl('zh')} lang="zh-CN" aria-current={lang==='zh'?'page':undefined}>中文</a><a href={languageUrl('en')} lang="en" aria-current={lang==='en'?'page':undefined}>EN</a></div><a className="button outline header-contact" href={KAKAO} {...external} onClick={()=>track('kakao_click',{origin:'header'})}>카카오톡 상담</a></div></header>
 <main id="main">
 {view==='home'&&<>
 <Storefront lang={lang} onSelect={beginPackage} onHelp={beginDestinationHelp}/>
 <ReviewStories lang={lang}/>
 </>}
 {view==='consult'&&<section className="consult-page"><button className="back-link" onClick={()=>go('home')}>홈으로 돌아가기</button><div className="consult-heading"><p className="section-kicker">{draft.mode==='private'?'전체 여행 상담':draft.mode==='single'?'필요한 서비스 상담':'여행 방법 추천'}</p><h1 ref={heading} tabIndex={-1}>내 여행을 조금만 알려 주세요.</h1><p>아직 정하지 못한 내용은 비워 두셔도 괜찮아요.<br/>{LIVE?'작성한 내용은 상담 담당자에게 전달됩니다.':'미리보기에서는 이 브라우저에만 저장됩니다.'}</p></div><div className="consult-layout"><form onSubmit={submit} noValidate>
 {draft.configuration?.inquiryText&&<section className="configuration-review"><h2>선택한 구성</h2><p>상세 선택 내용은 문의 메시지에 모두 포함됩니다.</p><details><summary>전체 구성 확인</summary><pre>{draft.configuration.inquiryText}</pre></details><a href={/^\/(?!\/)[a-zA-Z0-9/_?.=&%-]+$/.test(draft.configuration.sourcePath||'')?draft.configuration.sourcePath:'/booking.html'}>구성 수정하기</a></section>}<fieldset className="form-group"><legend>어떤 도움이 필요하세요?</legend><p className="form-help">{draft.configuration?.inquiryText?'서비스·날짜·인원 변경은 구성 수정에서 진행해 주세요.':'여러 서비스를 선택할 수 있습니다.'}</p><div className="service-options">{Object.entries(serviceNames).map(([key,label])=><label key={key} className={draft.services.includes(key)?'selected':''}><input disabled={Boolean(draft.configuration?.inquiryText)} name="services" type="checkbox" checked={draft.services.includes(key)} onChange={()=>toggleService(key)} aria-invalid={errors.services?'true':undefined} aria-describedby={errors.services?'services-error':undefined}/><span>{label}</span></label>)}</div><ErrorText name="services"/></fieldset>
 <fieldset className="form-group"><legend>언제, 몇 분이 떠나시나요?</legend>{draft.configuration?.dateDescription&&!draft.configuration?.date?<p>{draft.configuration.dateDescription}</p>:<div className="date-options">{[['exact','날짜를 정했어요'],['month','월만 정했어요'],['unknown','아직 미정이에요']].map(([key,label])=><label key={key} className={draft.dateMode===key?'selected':''}><input disabled={Boolean(draft.configuration?.date)} type="radio" name="dateMode" value={key} checked={draft.dateMode===key} onChange={()=>{update('dateMode',key);setErrors(e=>({...e,date:undefined,month:undefined}));}}/>{label}</label>)}</div>}<div className="form-row">{draft.dateMode==='exact'&&<div className="field"><label htmlFor="date">예상 출발 날짜</label><input {...fieldProps('date')} type="date" readOnly={Boolean(draft.configuration?.date)} min={today()}/><ErrorText name="date"/></div>}{draft.dateMode==='month'&&<div className="field"><label htmlFor="month">예상 여행 월</label><input {...fieldProps('month')} type="month" min={today().slice(0,7)}/><ErrorText name="month"/></div>}<div className="field"><label htmlFor="people">여행 인원 <span>필수</span></label><input {...fieldProps('people')} type="number" inputMode="numeric" min="1" max={partyLimit(draft)} readOnly={Boolean(draft.configuration?.people)} required/><ErrorText name="people"/></div></div></fieldset>
 <fieldset className="form-group"><legend>어떻게 연락드리면 될까요?</legend><div className="form-row"><div className="field"><label htmlFor="nickname">이름 또는 닉네임 <span>선택</span></label><input {...fieldProps('nickname')} autoComplete="nickname" maxLength="100" placeholder="편하게 부를 이름…"/></div><div className="field"><label htmlFor="contact">카카오톡 ID 또는 전화번호 <span>필수</span></label><input {...fieldProps('contact')} autoComplete="off" spellCheck={false} maxLength="200" required placeholder="카카오톡 ID 또는 010-1234-5678…"/><ErrorText name="contact"/></div></div><div className="field"><label htmlFor="notes">추가로 알려주실 내용 <span>선택</span></label><textarea {...fieldProps('notes')} rows="3" maxLength="2000" placeholder="부모님 동행, 가고 싶은 곳, 이동이 불편한 분…"/></div></fieldset>
 <details className="extra-details" open={draft.details} onToggle={e=>{if(e.currentTarget.open!==draft.details)update('details',e.currentTarget.open);}}><summary>상세 조건도 입력할래요 <span>선택</span></summary><div className="form-row"><div className="field"><label htmlFor="hotel">숙소 또는 희망 지역</label><input {...fieldProps('hotel')} maxLength="200" placeholder="호텔명 또는 무릉원…"/></div><div className="field"><label htmlFor="flight">항공편</label><input {...fieldProps('flight')} maxLength="100" placeholder="예: BX371…"/></div></div><div className="field"><label htmlFor="budget">예산 참고</label><input {...fieldProps('budget')} maxLength="200" placeholder="1인 예산 또는 전체 예산…"/></div></details>
 <div className="consent"><label><input id="consent" name="consent" type="checkbox" checked={draft.consent} onChange={e=>update('consent',e.target.checked)} aria-invalid={errors.consent?'true':undefined} aria-describedby={errors.consent?'consent-error':undefined}/><span>입력한 정보를 여행 상담 목적으로 이용하는 데 동의합니다.</span></label><p>{LIVE?<a href={lang==='ko'?'/privacy.html':'/'+lang+'/privacy.html'}>개인정보 처리 안내</a>:'미리보기 정보는 이 브라우저에만 보관됩니다. 실제 서비스의 개인정보 처리 안내는 정식 연결 시 별도로 제공합니다.'}</p><ErrorText name="consent"/></div>
 {!draftStored&&<p className="field-error" role="status">브라우저가 임시 저장을 허용하지 않습니다. 아래 내용을 복사해 카카오톡으로 문의해 주세요.</p>}
 {failed&&<div className="save-error" role="alert"><h3>{LIVE?'접수 확인이 필요합니다.':'아직 저장되지 않았습니다.'}</h3>{LIVE&&failureCode==='too-long'&&<p>선택 내용이 매우 많습니다. 전체 내용을 복사해 상담원에게 전달해 주세요. 내용은 삭제되지 않았습니다.</p>}{LIVE&&failureCode==='network'&&<p>서버 응답을 확인하지 못했습니다. 중복 접수를 피하려면 카카오톡으로 접수 여부를 확인해 주세요.</p>}<p>입력 내용은 화면에 남아 있습니다. 다시 시도하거나 내용을 복사해 카카오톡으로 문의해 주세요.</p><div className="inline-actions">{!['network','response'].includes(failureCode)&&<button type="submit" className="button outline">다시 저장하기</button>}<button type="button" className="text-link" onClick={()=>copy(inquiryText(draft,'',lang,LIVE))}>내용 복사</button><a href={KAKAO} {...external} onClick={()=>track('kakao_click',{origin:'save_failure'})}>카카오톡 열기</a></div><label className="sr-only" htmlFor="fallback-text">수동 복사용 상담 내용</label><textarea id="fallback-text" ref={copyArea} value={inquiryText(draft,'',lang,LIVE)} readOnly rows="7"/></div>}
 <div className="submit-area"><button className="button primary" type="submit" disabled={saving||(failed&&['network','response'].includes(failureCode))}>{saving?'접수 중…':'확인하고 상담 접수'}</button><p>{LIVE?'상담 접수이며, 예약 확정이 아닙니다.':'미리보기 저장이며, 실제 상담이나 예약은 접수되지 않습니다.'}</p></div><p className="notice" role="status" aria-live="polite">{notice}</p>
 </form><aside className="consult-aside"><h2>지금 생각한 여행</h2><dl><dt>서비스</dt><dd>{draft.services.map(x=>serviceNames[x]).join(' · ')||'선택 전'}</dd><dt>여행 시기</dt><dd>{dateLabel(draft)||'선택 전'}</dd><dt>인원</dt><dd>{draft.people||'—'}명</dd></dl><p>부담 없이 시작하세요.<br/>구체적인 일정과 견적은<br/>상담 후 함께 확인합니다.</p><a href={KAKAO} {...external} onClick={()=>track('kakao_click',{origin:'consult'})}>바로 카카오톡으로 문의</a></aside></div></section>}
 {view==='success'&&record&&<section className="success-page"><p className="section-kicker">{record.productionSubmitted?'상담이 접수되었습니다':'이 브라우저에 저장했습니다'}</p><h1 ref={heading} tabIndex={-1}>{record.productionSubmitted?'상담 요청을 접수했습니다.':<>다음은 카카오톡에서<br/>이야기 나눠요.</>}</h1><p className="success-intro">{record.productionSubmitted?'담당자가 선택한 조건과 연락처를 확인합니다.':'아래 번호는 미리보기용입니다. 실제 상담은 아직 접수되지 않았습니다.'}<br/>{record.productionSubmitted?'같은 내용을 다시 보내지 않아도 됩니다. 추가 문의에는 상담번호를 알려 주세요.':'문의 내용을 복사해 카카오톡에 붙여넣고 전송해 주세요.'}</p>{record.statusUrl&&<a className="button primary" href={record.statusUrl}>문의 진행 상황 확인</a>}<div className="reference-box"><span>{record.productionSubmitted?'상담번호':'미리보기 상담번호'}</span><strong>{record.reference}</strong><button className="text-link" onClick={()=>copy(record.reference)}>번호 복사</button></div><dl className="summary-grid"><div><dt>여행 시기</dt><dd>{dateLabel(record)}</dd></div><div><dt>인원</dt><dd>{record.people}명</dd></div><div><dt>서비스</dt><dd>{record.services.map(x=>serviceNames[x]).join(' · ')}</dd></div><div><dt>연락처</dt><dd>{record.contact}</dd></div></dl><div className="success-actions"><button className="button outline" onClick={()=>copy(text)}>문의 내용 복사</button><a className="button outline" href={KAKAO} {...external} onClick={()=>track('kakao_click',{origin:'success',reference:record.reference})}>카카오톡 열기</a></div><p className="notice" role="status" aria-live="polite">{notice}</p><label htmlFor="saved-text">전송할 문의 내용</label><textarea id="saved-text" ref={copyArea} value={text} readOnly rows="9"/><p className="success-note">복사만으로 전송되지 않습니다. 상담 후 예약 가능 여부와 최종 금액을 확인합니다.</p><div className="inline-actions"><button className="text-link" onClick={()=>{setDraft({...initialDraft(record.mode),...record});setFailed(false);go('consult',record.mode);}}>내용 수정하기</button><button className="text-link" onClick={()=>go('home')}>홈으로 돌아가기</button></div></section>}
 {view==='missing'&&<section className="success-page"><h1 ref={heading} tabIndex={-1}>저장한 내용을 찾을 수 없어요.</h1><p>미리보기 상담은 작성한 브라우저에서만 확인할 수 있습니다.</p><button className="button primary" onClick={()=>begin('help')}>새 상담 작성하기</button></section>}
 </main>
 <footer id="company"><div><a className="wordmark" href="?" onClick={e=>{e.preventDefault();go('home');}}>로투차</a><p>중국 여행을 더 가까이.</p></div><div><strong>현지 서비스 제공사</strong><p>张家界湘西国际旅行社有限公司</p><a href="/company.html" {...external}>회사·사업자 정보 확인</a></div><div><strong>여행 전 확인하세요</strong><a href="/tickets.html" {...external}>입장권 이용·변경·취소 조건</a><a href="/travel-info.html" {...external}>입국·결제·통신 준비</a><a href="/flights.html" id="flight-reference">항공편 참고</a><a href="/food-map.html">맛집·지도</a><a href="/privacy.html">개인정보 처리 안내</a><a href={KAKAO} {...external}>카카오톡 상담</a></div></footer>
 {!LIVE&&<details className="preview-tools"><summary>미리보기 테스트 도구</summary><p>다음 저장 시 실패 상태를 확인하거나, 이 브라우저의 테스트 기록을 삭제할 수 있습니다.</p><label><input type="checkbox" checked={failureTest} onChange={e=>setFailureTest(e.target.checked)}/> 다음 저장에서 실패 화면 보기</label><button className="text-link" onClick={()=>{try{localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(DRAFT_KEY);localStorage.removeItem('ltc-preview-events');}catch{}setDraft(initialDraft());setErrors({});setFailed(false);go('home');setNotice('이 브라우저의 테스트 기록을 삭제했습니다.');}}>테스트 기록 삭제</button></details>}
 </>,lang);
}
