import { formatEnglishPrice, englishPricingNote } from './english-pricing.mjs';
import React,{useEffect,useState} from 'react';
import ServiceIcon from './ServiceIcon.jsx';
import VideoGuides from './VideoGuides.jsx';
import TripCatalog from './TripCatalog.jsx';
import imageManifest from './image-manifest.json';
const copy={
 ko:{kicker:'로투차 · 현지에서 함께하는 중국 여행',title:'어디로 떠나고 싶으세요?',intro:'먼저 여행지와 일정을 살펴보세요.\n정해진 상품도, 나만의 여행도 현지 상담으로 준비합니다.',zjj:'장가계·후난',hainan:'하이난·싼야',zjjSub:'봉우리와 고성, 나에게 맞는 여행 속도',hainanSub:'바다와 섬, 하루 투어와 현지 생활',choose:'여행지 선택',explore:'여행 살펴보기',zjjHeading:'장가계 여행, 준비된 일정부터.',zjjText:'숙박 포함 여행을 비교하거나 입장권·차량·가이드만 골라 보세요. 결제 전 일정과 최종 견적을 함께 확인합니다.',hainanHeading:'하이난 여행도, 로투차와.',hainanText:'싼야의 하루 투어와 먹거리, 여행 준비를 한곳에서 확인하세요. 하이난 여행 전체 구성은 상담으로 요청할 수 있습니다.',services:'필요한 서비스만 고르세요',servicesText:'자유여행 일정은 그대로, 필요한 현지 서비스만 더하세요.',ticket:'관광지 입장권',ticketText:'방문일·연령·입장 옵션별 예상 금액',vehicle:'차량·공항 픽업',vehicleText:'인원·짐·이동 구간에 맞춘 차량 선택',guide:'현지 가이드',guideText:'날짜와 동행 일정에 맞춰 상담',day:'장가계 하루 투어',dayText:'하루 일정과 포함·불포함 비교',combo:'여러 서비스 함께',comboText:'입장권·차량·가이드를 한 번에 구성',custom:'더 자세히 맞춤 설정',customText:'관광지 13곳·객실·식사·속도를 직접 조정',help:'아직 정하지 못했어요',helpText:'날짜가 미정이어도 괜찮아요. 원하는 여행부터 알려 주세요.',helpAction:'여행 추천 상담',hainanHelp:'하이난 전체 여행 상담',hainanHelpText:'숙박·이동·가이드가 필요한 경우 희망 조건을 알려 주세요. 가능 여부와 별도 견적을 확인합니다.',hainanPrice:'성인 1인 참고 · 4명 이상 기준',hainanTerms:'2명부터 출발 가능 여부 확인. 2명은 1인 +45,000원, 3명은 +33,000원. 합승 차량·정해진 장소 집결이며 호텔 픽업·식사는 불포함입니다. 유아·성수기·최종 요금은 상담으로 확인하세요.',details:'일정·요금 조건 보기',food:'현지 맛집·생활 지도',prepare:'출발 준비 안내',support:'온라인 여행 지원',trust:['날짜·인원에 맞춘 최종 견적','상담 접수 후 일정 확인','예약 확정·결제는 상담 후'],monkey:'원숭이섬 + 송성가무쇼',binglang:'삥랑 빌리지 + 송성가무쇼',best:'천애해각 + 대소동천 + 유람선',monkeyDay:'월·수·금·일 · 출발 여부 확인',binglangDay:'화·목·토 · 출발 여부 확인',bestDay:'매일 · 출발 여부 확인',yen:'원',one:'1인'},
 zh:{kicker:'罗途查 · 中国当地旅行服务',title:'您想去哪里旅行？',intro:'先了解目的地与行程。\n现成线路与个性化旅行，都由当地顾问协助准备。',zjj:'张家界·湖南',hainan:'海南·三亚',zjjSub:'峰林与古镇，选择适合自己的旅行节奏',hainanSub:'海岛与海岸，一日游和当地生活',choose:'选择目的地',explore:'了解旅行',zjjHeading:'张家界旅行，从参考线路开始。',zjjText:'比较含住宿行程，或单独选择门票、用车与导游。付款前共同确认行程与最终报价。',hainanHeading:'海南旅行，同样有罗途查。',hainanText:'集中了解三亚一日游、美食及出行准备。海南全程安排也可提交需求咨询。',services:'只选需要的服务',servicesText:'保留自由行安排，按需补充当地服务。',ticket:'景区门票',ticketText:'根据日期、年龄与入园选项估算费用',vehicle:'用车·机场接送',vehicleText:'根据人数、行李和路线选择车辆',guide:'当地导游',guideText:'按日期与陪同行程咨询',day:'张家界一日游',dayText:'比较线路与包含、不含项目',combo:'组合多项服务',comboText:'一次配置门票、用车与导游',custom:'详细定制',customText:'自行调整13个景点、房间、饮食与节奏',help:'还没决定？',helpText:'日期未定也没关系，先告诉我们想怎样旅行。',helpAction:'咨询行程推荐',hainanHelp:'咨询海南全程旅行',hainanHelpText:'需要住宿、用车或导游时可提交需求，服务可能性与报价单独确认。',hainanPrice:'成人每人参考 · 4人及以上',hainanTerms:'2人起出发，须确认成团；2人每人另加45,000韩元，3人另加33,000韩元。拼车、指定地点集合，不含酒店接送及餐食。婴儿、旺季与最终费用咨询确认。',details:'查看行程与价格条件',food:'当地美食与生活地图',prepare:'出行准备指南',support:'在线旅行支持',trust:['按日期与人数确认最终报价','提交咨询后核对行程','预订确认与付款在咨询之后'],monkey:'猴岛 + 宋城演出',binglang:'槟榔谷 + 宋城演出',best:'天涯海角 + 大小洞天 + 游船',monkeyDay:'周一、三、五、日 · 出发需确认',binglangDay:'周二、四、六 · 出发需确认',bestDay:'每日 · 出发需确认',yen:'韩元',one:'每人'},
 en:{kicker:'LocalTourChina · Local support, thoughtfully planned',title:'Where would you like to go?',intro:'Explore the destination and itinerary first.\nChoose a prepared trip or plan your own with local guidance.',zjj:'Zhangjiajie · Hunan',hainan:'Hainan · Sanya',zjjSub:'Mountain scenery, old towns and your own pace',hainanSub:'Islands, coastlines, day tours and local life',choose:'Choose a destination',explore:'Explore trips',zjjHeading:'Zhangjiajie, with a place to start.',zjjText:'Compare trips with lodging or choose tickets, a vehicle or a guide. Confirm the itinerary and final quote before payment.',hainanHeading:'Discover Hainan with LocalTourChina.',hainanText:'Explore Sanya day tours, food and travel preparation. Ask about a complete Hainan itinerary if you need more support.',services:'Choose only what you need',servicesText:'Keep your independent itinerary and add local services.',ticket:'Attraction tickets',ticketText:'Estimates by date, age and entry options',vehicle:'Vehicles · airport transfers',vehicleText:'Choose for your party, luggage and route',guide:'Local guides',guideText:'Inquire for your dates and itinerary',day:'Zhangjiajie day tours',dayText:'Compare the itinerary, inclusions and exclusions',combo:'Combine services',comboText:'Configure tickets, vehicles and guides together',custom:'Detailed customization',customText:'Adjust 13 attractions, rooms, food and pace',help:'Still undecided?',helpText:'Dates can wait. Tell us how you would like to travel.',helpAction:'Ask for a recommendation',hainanHelp:'Ask about a full Hainan trip',hainanHelpText:'Tell us if you need lodging, transport or a guide. Availability and a separate quote require confirmation.',hainanPrice:'Reference per adult · party of 4+',hainanTerms:`Departures for 2+ require confirmation. For 2 people add ${formatEnglishPrice(45000)} each; for 3 add ${formatEnglishPrice(33000)} each. Shared transport and fixed meeting points; hotel transfers and meals excluded. Infant, peak-season and final rates require confirmation.`,details:'Itinerary & price conditions (Korean · KRW)',food:'Local food & map (Korean)',prepare:'Travel preparation',support:'Online travel support',trust:['Final quote for your dates and party','Your inquiry is reviewed by the team','Booking and payment follow consultation'],monkey:'Monkey Island + Songcheng show',binglang:'Binglang Valley + Songcheng show',best:'Tianya Haijiao + Daxiaodongtian + cruise',monkeyDay:'Mon / Wed / Fri / Sun · confirm departure',binglangDay:'Tue / Thu / Sat · confirm departure',bestDay:'Daily · confirm departure',yen:'KRW',one:'per adult'}
};

const entryCopy={
 ko:{title:'중국 여행, 필요한 만큼 함께해요.',intro:'입장권 한 장부터 우리 일행만의 여행까지.',heading:'어떤 도움이 필요하세요?',choose:'서비스 선택',selected:'선택한 여행지',available:'서비스와 예약 조건을 확인하세요.',ask:'가능 여부 문의',hainanNote:'하이난의 입장권·차량·가이드·맞춤여행은 가능 여부와 별도 견적을 먼저 확인합니다.',combine:'여러 서비스 함께 구성',trips:'준비된 여행 일정 보기',support:'유료 서비스 · 지원 시간과 범위 확인',items:[['ticket','입장권만 예약','방문일·연령별 옵션과 예상 금액'],['vehicle','공항 픽업·차량','공항 이동부터 하루 전용차량까지'],['guide','한국어 가이드','필요한 날짜와 일정에 맞춰 동행'],['day','하루 투어','하루 일정과 포함·불포함 확인'],['custom','우리끼리 맞춤여행','숙박·차량·가이드와 전체 일정 구성'],['support','온라인 여행 도움','여행 전 준비와 여행 중 한국어 지원']]},
 zh:{title:'中国旅行，需要多少帮助，由您选择。',intro:'从一张门票，到只属于同行人的旅行。',heading:'您需要什么帮助？',choose:'选择服务',selected:'当前目的地',available:'查看服务与预订条件。',ask:'咨询可否安排',hainanNote:'海南门票、车辆、导游与全程定制须先咨询可用情况和单独报价。',combine:'组合配置多项服务',trips:'查看现成旅行线路',support:'付费服务 · 请确认服务时段与范围',items:[['ticket','只订门票','查看日期、年龄与入园选项'],['vehicle','机场接送·用车','机场接送或按天包车'],['guide','韩语导游','按所需日期与行程安排陪同'],['day','一日游','查看行程及包含、不含项目'],['custom','同行人专属定制','住宿、车辆、导游与完整行程'],['support','在线旅行帮助','行前准备与旅途中的韩语支持']]},
 en:{title:'China travel, with the help you need.',intro:'From a single ticket to a private trip for your group.',heading:'What help do you need?',choose:'Choose a service',selected:'Selected destination',available:'Explore services and booking conditions.',ask:'Ask about availability',hainanNote:'Hainan tickets, vehicles, guides and private trips require an availability check and a separate quote.',combine:'Combine services',trips:'Explore prepared itineraries',support:'Paid service · check support hours and scope',items:[['ticket','Tickets only','Options and estimates for your dates and ages'],['vehicle','Airport transfers · vehicles','Airport rides or a private vehicle for the day'],['guide','Korean-speaking guide','Local company for your dates and itinerary'],['day','Day tours','Compare itineraries, inclusions and exclusions'],['custom','Private trip','Plan lodging, vehicles, guides and your itinerary'],['support','Online travel help','Korean-language help before and during your trip']]}
};
const entryRoutes={ticket:'tickets.html',vehicle:'vehicles.html',guide:'local-guide.html',day:'day-tours.html',custom:'private-tour.html?mode=custom',support:'online-guide.html'};

const brandCopy={ko:{hello:'반가워요, 로투차입니다.',caption:'중국 여행을 더 가까이.',note:'궁금한 여행, 편하게 이야기해요.'},zh:{hello:'您好，欢迎来到罗途查。',caption:'让中国旅行更亲近。',note:'聊聊您想要的旅行。'},en:{hello:'Hello, we’re LocalTourChina.',caption:'A little closer to China.',note:'Tell us about the trip you have in mind.'}};
const route=(path,lang)=>lang==='zh'?'/zh/'+path:lang==='en'?'/en/'+path:'/'+path;
function Photo({src,alt,srcSet,priority=false,sizes='(max-width: 700px) 100vw, 48vw'}){return <img src={src} srcSet={srcSet||imageManifest[src]?.srcSet} sizes={sizes} width="960" height="640" alt={alt} loading={priority?'eager':'lazy'} fetchPriority={priority?'high':'auto'} decoding="async"/>;}
export default function Storefront({lang='ko',onSelect,onHelp}){
 const t=copy[lang]||copy.ko;
 const entry=entryCopy[lang]||entryCopy.ko;
 const brand=brandCopy[lang]||brandCopy.ko;
 const readDestination=()=>new URLSearchParams(location.search).get('destination')==='hainan'?'hainan':'zhangjiajie';
 const [destination,setDestination]=useState(readDestination);
 useEffect(()=>{const listener=()=>setDestination(readDestination());window.addEventListener('popstate',listener);return()=>window.removeEventListener('popstate',listener)},[]);
 function choose(next){if(next===destination)return;setDestination(next);const url=new URL(location.href);url.searchParams.set('destination',next);history.pushState({},'',url);}
 const isHainan=destination==='hainan';
 const detailRoute=(id)=>route('day-tours.html?destination=sanya&tour='+id,lang==='en'?'ko':lang);

 return <div className="storefront warm-storefront" id="services">
 <section className="home-hero scenic-hero" data-destination={destination} aria-label={entry.title}><div className="home-hero-copy"><p className="section-kicker">{t.kicker}</p><h1>{entry.title}</h1><p>{entry.intro.split('\n').map((line,i)=><React.Fragment key={line}>{i>0&&<br/>}{line}</React.Fragment>)}</p><div className="home-hero-actions"><a className="button primary" href="#service-entry">{entry.choose}</a><button className="text-link" onClick={()=>onHelp(destination)}>{t.helpAction}</button></div></div><div className="brand-welcome"><Photo src={isHainan?'/assets/media/sanya/tianya-haijiao-jpg-849.webp':'/assets/hero-jpg-1920.webp'} alt={isHainan?t.hainan:t.zjj} priority sizes="100vw" srcSet={isHainan?undefined:imageManifest['/assets/hero-jpg-1920.webp'].srcSet+', /assets/hero-jpg-2478.webp 2478w'}/></div></section>

 <div id="destination-products"><section className="intent-services" id="service-entry" aria-labelledby="service-entry-title"><header className="intent-heading"><div><p className="section-kicker">{lang==='en'?'01 / YOUR WAY TO TRAVEL':lang==='zh'?'01 / 您的旅行方式':'01 / 나만의 여행 방식'}</p><h2 id="service-entry-title">{entry.heading}</h2></div><div className="intent-destination"><span className="destination-label">{t.choose}</span> <nav className="destination-grid" aria-label={t.choose}>{[['zhangjiajie',t.zjj,t.zjjSub,'/assets/forest-jpg-480.webp'],['hainan',t.hainan,t.hainanSub,'/assets/media/sanya/tianya-haijiao-jpg-640.webp']].map(([key,title,description,src])=><button key={key} type="button" className="destination-button" data-active={destination===key} aria-pressed={destination===key} aria-controls="destination-products" onClick={()=>choose(key)}><span><strong>{title}</strong></span></button>)}</nav>{isHainan&&<p className="intent-description">{entry.hainanNote}</p>}</div></header><div className="intent-grid">{entry.items.map(([key,title,description])=>{const inquiry=isHainan&&['ticket','vehicle','guide','custom'].includes(key);const content=<><ServiceIcon kind={key}/><strong>{title}</strong><span className="intent-detail">{description}</span><span className="intent-action">{inquiry?entry.ask:key==='support'?entry.support:<span aria-hidden="true">↗</span>}</span></>;return inquiry?<button className="intent-card" type="button" key={key} onClick={()=>onHelp(destination)}>{content}</button>:<a className="intent-card" key={key} href={isHainan&&key==='day'?'#prepared-trips':route(entryRoutes[key],lang)}>{content}</a>})}</div><nav className="intent-secondary" aria-label={entry.choose}>{!isHainan&&<a href={route('multi-booking.html',lang)}>{entry.combine} →</a>}<a href="#prepared-trips">{entry.trips} ↓</a></nav></section><VideoGuides lang={lang} destination={destination}/><header id="prepared-trips" className="destination-intro"><p className="section-kicker">{isHainan?t.hainan:t.zjj}</p><h2>{isHainan?t.hainanHeading:t.zjjHeading}</h2><p>{isHainan?t.hainanText:t.zjjText}</p></header>
 {!isHainan?<><TripCatalog lang={lang} onSelect={onSelect} compactHeading/><div className="store-help"><div><h3>{t.help}</h3><p>{t.helpText}</p></div><button className="button outline" onClick={()=>onHelp(destination)}>{t.helpAction}</button></div></>:<><div className="hainan-grid">{[['sanya-monkey','monkey',148900,'monkey-island'],['sanya-binglang','binglang',148800,'binglang-village'],['sanya-best','best',119800,'tianya-haijiao']].map(([id,key,price,image])=><article className="hainan-card" key={id}><Photo src={'/assets/media/sanya/'+image+'-jpg-640.webp'} alt={t[key]} sizes="(max-width: 700px) 100vw, 33vw"/><div><p className="section-kicker">{t[key+'Day']}</p><h3>{t[key]}</h3><p className="trip-price"><strong>{lang==='en'?formatEnglishPrice(price):<>{price.toLocaleString()} {t.yen}</>}</strong></p><p>{t.hainanPrice}</p><p className="trip-catalog-price-note">{lang==='ko'?'2~3명 추가금 · 합승 · 호텔 픽업·식사 불포함':lang==='zh'?'2–3人另加费 · 拼车 · 不含酒店接送及餐食':'2–3 people: surcharge · shared transport · meals and hotel transfers excluded'}</p><a className="button primary" href={detailRoute(id)}>{t.details}</a></div></article>)}</div><p className="hainan-conditions">{t.hainanTerms}</p>{lang==='en'&&<p className="trip-catalog-price-note">{englishPricingNote}</p>}<div className="store-help"><div><h3>{t.hainanHelp}</h3><p>{t.hainanHelpText}</p></div><button className="button outline" onClick={()=>onHelp(destination)}>{t.helpAction}</button></div><nav className="service-choice-grid hainan-guides"><a className="service-choice" href={(lang==='zh'?'/zh':'')+'/food-map.html?region=sanya'}><h3>{t.food}</h3><span aria-hidden="true">→</span></a><a className="service-choice" href={route('travel-info.html',lang)}><h3>{t.prepare}</h3><span aria-hidden="true">→</span></a><a className="service-choice" href={route('online-guide.html',lang)}><h3>{t.support}</h3><span aria-hidden="true">→</span></a></nav></>}
 </div><div className="trust-strip">{t.trust.map((line,i)=><p key={line}><span>{i+1}</span>{line}</p>)}</div></div>;
}
