import React,{useEffect,useRef,useState} from 'react';
import videos from './video-guides.json';
import {createVideoPlayer,selectVideos,videoCategories,matchesVideoCategory} from './video-player.mjs';
import './video-guides.css';
const copy={ko:{kicker:'영상으로 먼저 만나는 여행',title:'길을 알면, 여행이 더 편해져요.',intro:'로투차의 현장 영상으로 동선과 풍경을 미리 살펴보세요.',watch:'페이지에서 영상 보기',external:'YouTube에서 열기',channel:'로투차 YouTube 채널',loading:'선택하면 YouTube 플레이어를 불러옵니다.'},zh:{kicker:'先用视频了解旅行',title:'先看懂路线，出发更从容。',intro:'通过罗途查的实地视频，提前了解景区路线与风景。',watch:'在页面内观看',external:'在 YouTube 打开',channel:'罗途查 YouTube 频道',loading:'点击后才会加载 YouTube 播放器。'},en:{kicker:'See the journey first',title:'A clearer route. A calmer trip.',intro:'Explore the routes and scenery with LocalTourChina’s on-location videos.',watch:'Watch here',external:'Open on YouTube',channel:'LocalTourChina on YouTube',loading:'The YouTube player loads only after you choose a video.'}};
export default function VideoGuides({lang='ko',destination='zhangjiajie'}){
 const [category,setCategory]=useState('all');
 const t=copy[lang]||copy.ko,host=useRef(null),player=useRef(null),items=selectVideos(videos,{destination,category},6),hasItems=items.length>0;
 const categoryLabels={ko:{all:'전체',routes:'관광지·동선',transport:'공항·차량',local:'현지 생활·가이드',prepare:'여행 준비'},zh:{all:'全部',routes:'景点·路线',transport:'机场·用车',local:'当地生活·导游',prepare:'旅行准备'},en:{all:'All',routes:'Sights & routes',transport:'Airport & vehicles',local:'Local life & guides',prepare:'Preparation'}}[lang]||{};
 const categories=videoCategories.filter(c=>c==='all'||videos.some(v=>v.destination===destination&&matchesVideoCategory(v,c)));
 useEffect(()=>{if(!host.current)return;player.current=createVideoPlayer(host.current,{lang});return()=>{player.current?.dispose();player.current=null;};},[lang,hasItems]);
 useEffect(()=>{player.current?.close({restoreFocus:false});setCategory('all');},[destination]);
 useEffect(()=>{player.current?.close({restoreFocus:false});},[category]);
 if(!items.length)return null;
 return <section className="video-guides" aria-labelledby="video-guides-title"><div className="video-guides-heading"><div><p className="section-kicker">{t.kicker}</p><h2 id="video-guides-title">{t.title}</h2><p>{t.intro}</p></div><a href="https://www.youtube.com/@Lctch" target="_blank" rel="noopener noreferrer">{t.channel} ↗</a></div><div className="video-category-controls" role="group" aria-label={lang==='ko'?'영상 주제':lang==='zh'?'视频主题':'Video topics'}>{categories.map(key=><button type="button" key={key} aria-pressed={category===key} onClick={()=>setCategory(key)}>{categoryLabels[key]}</button>)}</div><p className="video-load-note">{t.loading}</p><div ref={host} className="video-player-host" hidden/><p className="video-scroll-hint">{lang==='ko'?'옆으로 넘겨 더 보기 →':lang==='zh'?'向右滑动查看更多 →':'Scroll sideways for more →'}</p><div className="video-guides-grid">{items.map(v=><article className="video-guide-card" key={v.id}><button type="button" className="video-guide-open" aria-expanded="false" onClick={e=>player.current?.open(v,e.currentTarget)} aria-label={`${t.watch}: ${v.title[lang]||v.title.ko}`}><span className="video-guide-image"><img src={v.thumbnail} width="640" height="360" loading="lazy" decoding="async" referrerPolicy="no-referrer" alt="" onError={e=>{e.currentTarget.hidden=true;e.currentTarget.parentElement.dataset.imageError='true';}}/><span className="video-image-fallback" aria-hidden="true">LOCALTOUR CHINA<small>YouTube · {lang==='ko'?'여행 영상':lang==='zh'?'旅行视频':'Travel film'}</small></span></span><span className="video-guide-copy"><span className="video-guide-title">{v.title[lang]||v.title.ko}</span>{v.historicalPricing&&<small className="video-historical-note">{lang==='ko'?'영상 속 과거 가격 · 현재 견적 확인':lang==='zh'?'视频含历史价格，请以当前报价为准':'Historical prices shown; check today’s quote.'}</small>}<span className="video-watch-label"><span aria-hidden="true">▶ </span>{t.watch}<small>{v.format==='short'?'Shorts':'YouTube'}</small></span></span></button><a className="video-external-link" href={v.url} target="_blank" rel="noopener noreferrer">{t.external} ↗</a></article>)}</div><p className="video-context-note">{lang==='ko'?'영상 촬영 이후 운영 방식이 달라질 수 있으니 방문일 안내를 확인해 주세요.':lang==='zh'?'视频拍摄后运营安排可能变化，请确认实际到访日期的通知。':'Operations may have changed since filming. Check guidance for your visit date.'}</p></section>;
}
